### ISSUE TITLE
Password reset link is wrong

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-backend-node#102]
The generated link is wrong, it is missing the route between the FQDN and the token. Here's an example (truncated for security):

`http://tenders.exposed/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZAMHgxOS5uZXQiLCJpYXQiOjE1NDY1MzQ4MTMsImV4cCI6MTU0NjUzODQxM30.somemorecharacters`

It should address the route `/account/recover?t=`

**Comment by georgiana-b** [comment]
@nightsh I will close this as it was fixed AFAIK. Feel free to reopen if needed.
