### ISSUE TITLE
Set up authentication backend

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-backend-node#23]
We need to authenticate users against our API.

We will have JWT based authentication and 3rd party authorization with GitHub and Twitter as alternatives.

Even if the users login with 3rd party providers they still need to be stored in the DB because we need to link their resources to an account so for such users we will only store email and provider.

For people who don't want to use third parties we will provide classical registration with email confirmation and JSON Web Token based authentication.

If at some point a user authenticates with 3rd party even though their email is already present in our db we will not create another user account, we will just add that provider to the existing account. So email should work as unique identifier for users. 

Users will be connected to networks and should preferably be stored in our OrientDB database.

**Comment by georgiana-b** [comment]
The important logic (creating users, updating the account with providers, logging in, etc.) should be tested.

**Comment by georgiana-b** [comment]
After more discussion we decided to have a unified strategy instead of 2 (one for third-party one for built-in authentication). To quote Edgar:

> In all scenarios we need to generate access and refresh tokens, give it to client and client should make all the requests to hidden resources with his access and refresh token.
