### ISSUE TITLE
Create endpoint for lost account recovery

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-backend-node#32]
I just started poking around the auth implementation, aiming for a quick integration with the existing frontend.

So far I only explored the endpoints, looking for all the thing I might need in order to provide a full user experience. One issue I found is that there is no endpoint for recovering an account (e.g. "lost password" endpoint).

The desired user story would be:

* user has an unauthenticated endpoint where she can `POST` something like this: `{ "email": "contact@emxample.org" }`
* server registers the request and generates a one time password refresh token
* user receives an email with the password refresh token
  * user `POST`s back the password refresh token together with the new password
* server processes this as:
  * validates token
  * expires the token
  * changes user password
  * returns HTTP 200 for the request

**Comment by georgiana-b** [comment]
@edgarmarkosov This is something very important that we forgot.

**Comment by edgarmarkosov** [comment]
@georgiana-b I agree with you.
