### ISSUE TITLE
No password confirmation in payloads

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-backend-node#33]
For account creation, there is only a `password` field required, validated and processed. Since there is no pwd confirmation in place, this means:

a) account created via HTTP requests (very unlikely) will be prone to password errors
b) we have to implement confirmation client side, whatever client we might use (easy to do)
c) if user enters a wrong password, then there's no way to get a hold of her account (see #32)

Shall we adjust swagger, or leave it as it is? I'm not sure if the added benefits are indeed beneficial enough, hence the `question` tag.

**Comment by georgiana-b** [comment]
TBH I think this is ok as long as we provide account recovery so I'll close it.
