### ISSUE TITLE
Some elements not in payload even if present in the API documentation

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-backend-node#72]
`isEUFunded`, `procedureType` and `selectionMethod` not present in the payload.

**Comment by georgiana-b** [comment]
They don't appear in the payload unless they have a value and they don't have a value becuase I forgot to restart the import. I started it now and I'll keep you posted.

**Comment by georgiana-b** [comment]
I reimported the data so the dev db contains all these fields now but some tenders just don't have values for them. For example if there is no information about funding `isEUFunded` will be null and will not appear in the response.

Those that do have funding info have the field in the response like [this one](https://dev.api.tenders.exposed/networks/c63425ac-6ecb-45fb-8dd5-a2131522834c/tenders/387970af-67a7-4095-aed4-542159597b23)

As I mentioned before, field who don't appear as required (with a red `*`) in Swagger are not guaranteed to have values all the time.
@ca1yps0 You will just have to manage the case when they are `undefined`.

@zufanka If you think they should always have a value we'll have to give them defaults.

I'll close this as it's no longer true.
