### ISSUE TITLE
Company and authority IDs

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-backend-node#73]
Do we have company and authority IDs?
This is what the URLs look like:

https://opentender.eu/ro/authority/EU_body_adde6e78adcfed630cd8eafccc11936ba4301a880a41c97388e809f9b26bb67c

https://opentender.eu/ro/company/EU_body_21640c1fec3e431c23c02731c8b197498e3c7129af7ee839aef8d81777745f33

**Comment by georgiana-b** [comment]
Turns out this is just the new format of actor IDs in the opentender.eu data so there's nothing to worry about.
