### ISSUE TITLE
Bids don't add up

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-backend-node#75]
![image](https://user-images.githubusercontent.com/2411066/36944846-5e3ae2fe-1fa4-11e8-9675-a29ad3577fe4.png)

[this network](https://elvis-ember-new-backend.herokuapp.com/network/163ce285-fc46-4d07-bce8-118079732999)

**Comment by georgiana-b** [comment]
I just created [another network with the same query](https://dev.api.tenders.exposed/networks/534999b2-9409-47b7-9cf4-5559cdc960fd) as this network and the value of this node is correct (6).
I think you might have made the network at a time while the data was reimporting and there were only 2 bids but by the time you checked the details the other 4 bids were imported. 

I'll close this for now but feel free to reopen it if this happens to you again.
