### ISSUE TITLE
Keep only awarded tenders

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-backend-node#96]
We currently keep all tenders and lots in the db. However, we only aggregate on the bids and only the `awarded` (and maybe `cancelled`) tenders have bids. The others (`announced` and `prepared`) only take out space for no good reason. Quite a lot of it too since they account for about half of the 1.2 million lots.

Since we're already struggling with the size of the dB I think it would be a great idea to remove the lots that haven't been awarded and the tenders that have no awarded lots.

**Comment by georgiana-b** [comment]
@zufanka What do you think?

**Comment by zufanka** [comment]
@georgiana yes, please!
Also feel free to get rid of the cancelled ones.
