### ISSUE TITLE
Error while merging nodes

### ISSUE THREAD

**Issue by zufanka** [tenders-exposed/elvis-backend-node#97]
Tried to merge nodes on [this network](https://tenders.exposed/network/deed1a97-0fd7-45ce-b384-f8fa2a236183/bidders)

The merge however never ends

![image](https://user-images.githubusercontent.com/2411066/44787519-aadfb880-ab97-11e8-8842-1e74bdc9d6ca.png)

I have found only this warning in the console:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.tenders.exposed/networks/deed1a97-0fd7-45ce-b384-f8fa2a236183/clusters. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by zufanka** [comment]
I see now that this network has already merged .. so it merges the nodes, but the "Merging nodes" message never goes away.

**Comment by zufanka** [comment]
I tried to merge again within the network and that has worked fine

**Comment by zufanka** [comment]
Tried to cluster this network, no luck :( https://tenders.exposed/network/b91f582d-1b68-46a0-b3f3-be5a6c6b5b2d/bidders

**Comment by georgiana-b** [comment]
Hi @zufanka! I just looked into this and the API is working as expected. 

I just created a network and a cluster within it using the API with no problem.

@nightsh This seems to be a frontend issue. Could you look into please?

**Comment by zufanka** [comment]
thank you !
